version: '3.3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    ports:
      - '27017:27017'
    volumes:
      - ./mongodb/mongo-data:/data/db
      - ./mongodb/mongo-config:/data/configdb
    networks:
      - mongo_backend_network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mypassword
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123456
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017/
    networks:
      - mongo_backend_network

networks:
  mongo_backend_network:
    driver: bridge
